---
title: "Breakable Toy Deliverable #3 - Final User Stories, Acceptance Criteria, and ER Diagrams"
type: "challenge"
description: "Your final pass at user stories, acceptance criteria, and ER diagrams for your Breakable Toy."
tags: "breakable-toy"
ignore:
- "breakable-toy-deliverable-3.md"
